server {
    listen 8080;
    server_name _;
    location /admin { proxy_pass http://approval:5000; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header Cookie $http_cookie; }
    location /login { proxy_pass http://approval:5000; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header Cookie $http_cookie; }
    location /demande { proxy_pass http://approval:5000; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header Cookie $http_cookie; }
    location /submit { proxy_pass http://approval:5000; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header Cookie $http_cookie; }
    location /check-status { proxy_pass http://approval:5000; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header Cookie $http_cookie; }
    location /approve { proxy_pass http://approval:5000; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header Cookie $http_cookie; }
    location /reject { proxy_pass http://approval:5000; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header Cookie $http_cookie; }
    location /update-status { proxy_pass http://approval:5000; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header Cookie $http_cookie; }
    location /excel { proxy_pass http://approval:5000; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header Cookie $http_cookie; }
    location / { proxy_pass http://frontend:8080; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
}
