server.port=5000
spring.datasource.url=jdbc:h2:file:${DB_PATH:./data/approval_db};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.servlet.session.timeout=60m
spring.thymeleaf.cache=false
vcard.api.base=${VCARD_API_BASE:http://localhost:8767}
vcard.api.email=${VCARD_API_EMAIL:admin@afrilandfirstbank.com}
vcard.api.password=${VCARD_API_PASS:admin}
vcard.front.url=${VCARD_FRONT_URL:http://localhost:8801}
