sonar.projectKey=angular
sonar.projectName=Digital Card Web (Angular)

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,karma.conf.js

sonar.sourceEncoding=UTF-8
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Bootstrap / config files that cannot be unit tested meaningfully
sonar.coverage.exclusions=karma.conf.js,src/app/app.config.ts,src/main.ts,src/**/*.routes.ts
